import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";
import Sidebar from "./components/sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen bg-[#F5F5F9] ">
          <div className=" flex h-screen  ">
          <Sidebar />
          </div>
        
          <div className=" flex-1 overflow-y-auto px-5   ">
            <Header/>
            {children}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
