import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex spa h-screen  ">
          <div className=" w-1/6 ">
          <Sidebar />
          </div>
          
          <div className=" w-10/12 p-4 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
