import type { Metadata } from "next";
import { Nunito_Sans } from 'next/font/google';
import "./globals.css";
import Sidebar from "./components/sidebar";
import Navbar from "./nav/navbar";
import { NavbarTitleProvider} from './nav/NavbarTitleContext';
import LayoutWithNavbar from './nav/layoutWithNavbar';
const nunito = Nunito_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-nunito',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={nunito.variable}>
      <body className="font-nunito">
        <NavbarTitleProvider>
          <LayoutWithNavbar>{children}</LayoutWithNavbar>
        </NavbarTitleProvider>
      </body>
    </html>
  );
}
